full_rebuild: true
title: "Container Fundamentals Workshop"
tracking: "dockerworkshop"
author: Abdoul-Hakim Afraitane
encoding: utf-8
defaults:
  - values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
  - entries
sass:
  sass_dir: _sass
  style: "compressed"
exclude: [.git, .gitignore, README.md, .sass-cache]
plugins:
  - "jekyll-github-metadata"
